# Updated Custom Resource Definition for an Anvil.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fulfillmentcenters.foo-corp.com
spec:
  group: foo-corp.com
  versions:
    - name: v1
      served: true
      storage: false
    - name: v2
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: fulfillmentcenters
    singular: fulfillmentcenter
    kind: FulfillmentCenter
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - address
          properties:
            address:
              type: string
